apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-pdf
  namespace: demo
  labels:
    app: django-pdf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-pdf
  template:
    metadata:
      labels:
        app: django-pdf
    spec:
      containers:
        - name: django-pdf
          image: django-pdf:dev

---
kind: Service
apiVersion: v1
metadata:
  name: django-pdfr
  namespace: demo
spec:
  type: NodePort
  selector:
    app: django-pdf
  ports:
    - protocol: TCP
      name: http
      port: 8000
      targetPort: 8000
      nodePort: 32004